#!/bin/sh
# 
# 
# Default-Start:     1 2 3 4 5
# Default-Stop:      0 6
# 
# 
start() {
    python3 /home/abw/CODE/abweb/DDNS/DDNS.py start
}

stop() {
    python3 /home/abw/CODE/abweb/DDNS/DDNS.py stop
}

case "$1" in 
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "$0 start|stop"
        exit 1
esac